typography_spectrum: 0.43290896457619965
color:
  brandColors:
    - '#e9e9e9'
    - '#656668'
    - '#999a9c'
    - '#cccccc'
    - '#050505'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.41449044016189873
analytics:
  google: null
  facebook: null
  twitter: null
name: Savage
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: My Site
    url: 'http://gharv.com'
    type: external
favicon: null
title: SAVAGE
purpose: []
