name: Savage
favicon: null
layout_spectrum: 0.41449044016189873
typography_spectrum: 0.43290896457619965
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.42913265875540674
  lightness: 0.20543652796186507
  saturation: 0.004321189597249031
  rhythmicContrast: 0.9143385468050838
purpose: []
