name: Savage
favicon: null
layout_spectrum: 0.41449044016189873
typography_spectrum: 0.43290896457619965
title: SAVAGE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e9e9'
    - '#656668'
    - '#999a9c'
    - '#cccccc'
    - '#050505'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
